from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd + '/../inc']

group = DefineGroup('IoT', src, depend = ['PKG_USING_RTLINK_TYPE'], CPPPATH = CPPPATH)

Return('group')
